lib/script.js
test/script.js

ESM has no header like common-js, and files start with a `file://` prefix.

feat: support ESM

---

.travis.yml
README.md
lib/script.js
package-lock.json
package.json
tap-snapshots/test-script.js-TAP.test.js
test/script.js

switches to using [c8 for coverage](https://github.com/bcoe/c8/pull/22) now that coverage support has been landed in Node.js `10.10.0`.

chore: switch to c8 for coverage

---

index.js
lib/script.js
test/script.js

BREAKING CHANGE: we no longer attempt to detect ESM modules, rather the consumer sets a wrapper length

feat: allow wrapper length to be configured

---

lib/script.js

Windows has a `\r\n` line separator, which was causing off by one errors in coverage.

fix: windows has \r\n line separator

---

.travis.yml
lib/script.js
tap-snapshots/test-script.js-TAP.test.js
test/script.js

By default in Node 11+ there is no longer a wrapper around scripts, see:
https://github.com/nodejs/node/pull/21573

feat: Node 11 no longer wraps scripts by default

---

lib/source.js

In Node.js 10, it was possible for the column position to be less than 1 after subtracting the wrapper; this problem should go away once https://github.com/nodejs/node/pull/27124 is released.

fix: column could be < 1 when wrapper taken into account

---

.travis.yml
README.md
lib/line.js
lib/source.js
lib/v8-to-istanbul.js
package-lock.json
package.json
tap-snapshots/test-v8-to-istanbul.js-TAP.test.js
test/source.js

hard to reach uncovered lines can now be ignored using the special:
`/* c8 ignore next */` comment.

 feat: allow uncovered lines to be ignored with special comment

---

index.d.ts
index.js
lib/v8-to-istanbul.js

This is a first, quick, pass for #33. It does not have docs or tests as I'd like to get some feedback on it if it's the correct approach, or if we should have different `load` methods depending on if we want to read from fs or not
Fixes #33
(includes #35)

 feat: add a sources option allowing to bypass fs operations

---

lib/v8-to-istanbul.js
package.json

currently the logic for handling sourceRoot does not attempt to take into account `process.cwd()`, this means it can't work for relative paths in most environments.

fix: logic for handling sourceRoot does not take into account process.cwd()

---

lib/v8-to-istanbul.js

fixes: https://github.com/bcoe/c8/issues/111

fix: Node >10.16.0 now uses new module wrap API

---

lib/v8-to-istanbul.js

As [`.load()` is already an async function](https://github.com/istanbuljs/v8-to-istanbul/blob/v3.2.3/lib/v8-to-istanbul.js#L30), we can use `fs.promises.readFile()` inside the method.

chore: load a source file asynchronously

---

lib/v8-to-istanbul.js

It was possible for `this.sources.sourceMap.sourcemap.sourcesContent` to be undefined.

fix: protect against undefined sourcesContent

---

lib/v8-to-istanbul.js
test/fixtures/scripts/empty.compiled.js
test/fixtures/scripts/empty.compiled.js.map
test/v8-to-istanbul.js

For source maps, the sources property can potentially be an empty array if mappings
doesn't provide any information about its origin. For example if you compile an empty
js file with babel, a valid sourcemap can be created with `[]` for `sources`. Here
we add a fallback to `file` in this case and adds a fixture to test for it.
The new test fixtures `empty.js`, `emtpy.compiled.js` and `empty.compiled.js.map`
simulate this scenario for a unit test.
This is bug 1 from the previous PR. To see the problem in action, comment out the fix line in `lib/v8-to-istanbul` and you will see the crash that happens when we try to load a sourcemap like this.

fix: handle sourcemap `sources` emtpy edge case

---

lib/v8-to-istanbul.js
test/fixtures/scripts/relative-source-root.compiled.js
test/fixtures/scripts/relative-source-root.compiled.js.map
test/source.js
test/v8-to-istanbul.js

Fixes the issue recorded in https://github.com/istanbuljs/v8-to-istanbul/issues/99
For the test case, you can run the new unit test on master as is and you can see the invalid source resolution. With the fix the path is correct.

fix: handle relative sourceRoots in source map files

---

lib/v8-to-istanbul.js
tap-snapshots/test-v8-to-istanbul.js-TAP.test.js
test/v8-to-istanbul.js

In order to correctly load HTML reports, the [resolving logic described in the V3 source map spec](https://sourcemaps.info/spec.html#h.75yo6yoyk7x5) needs to be applied.
I've added a TODO note, that it would be nice to simplify our logic a bit, such that this is always applied as a final step. Currently we resolve 1:1 source map paths during initialization, and 1:many as a final step.
CC: @MoLow the 
Refs #102

fix: address path related bugs with 1:many source maps

---

index.d.ts

Upgrading to v5 gives a type error in Jest:

fix: add missing type in TS definition

---

lib/v8-to-istanbul.js

I have js files generated by tsc which have the source map with a `sourcesContent` property embedded as base64 data url. This fix makes `v8-to-istanbul` pick that up.

feat: add support for 1:1 sourcesContent

---

lib/v8-to-istanbul.js
tap-snapshots/test-v8-to-istanbul.js-TAP.test.js
test/fixtures/branches.js
test/fixtures/scripts/branches.js

Due to an off by one error when determining blocks in v8, the first character of a block range is sometimes the `\n` from the prior line:
In the example:
```js
function fn() {
return true;
/* c8 ignore next */
console.log('never runs');
}
fn();
```
One of the blocks is characters 30 - 83, or:
```
\n  /* c8 ignore next */\n  console.log('never runs');\n
```
It should not be possible for a conditional block to begin with a single character, so I believe we can address this problem by making the logic that calculates branches exclusive vs., inclusive, when it overlaps with the prior line.
Refs: https://github.com/bcoe/c8/issues/254

fix!: address off by one error processing branches

---

.nycrc
lib/source.js
package-lock.json
package.json
test/fixtures/shebang.js
test/utils/run-fixture.js

As of Node 13, the shebang is parsed by v8, see: https://github.com/nodejs/node/pull/27375

fix: drop special shebang handling

---

README.md
lib/source.js
test/source.js

I implemented the idea I shared here: https://github.com/bcoe/c8/issues/271
```js
/* c8 ignore start */
function dontMindMe() {
// ...
}
/* c8 ignore stop */
```
I refactored the function that parses for these `c8 ignore` comments to have no side effects; I also split up the "on its own line" case to be handled separately from the "ignore next n" case. My goal was to make the function and its usage more readable: let me know if I failed in that goal.

feat: support comment c8 ignore start/stop

---

lib/v8-to-istanbul.js

If a generated sourcemap has no sources / files (can happen from typescript type only imports) the originla source files path should be tried.
fixes #134

fix: use original source path if no sources

---

lib/v8-to-istanbul.js

When bundling this [file](https://github.com/browserify/node-util/blob/master/util.js) with esbuild and getting the v8 coverage with playwright `_branchesToIstanbul` and `_functionsToIstanbul` hanged.
These 2 functions actually should throw an error but it is swallowed for some reason.
This PR just ignores if it can't find the source line for the current branch or function.

fix: undefined line in branches and functions

---

README.md
index.d.ts
lib/v8-to-istanbul.js
test/v8-to-istanbul.js

Adds a `destroy` function as counterpart to the existing `load` to cleanup allocated resources after usage, especially memory allocated by the `SourceMapConsumer` from the *source-map* dependency.
Currently the converter creates a new `SourceMapConsumer` during the load operation, however this gets never destroyed properly. Documentation states that "When the SourceMapConsumer will no longer be used anymore, you must call its destroy method." (https://github.com/mozilla/source-map/blob/58819f09018d56ef84dc41ba9c93f554e0645169/README.md#new-sourcemapconsumerrawsourcemap). Failing to cleanup the consumer can trigger errors such as mozilla/source-map/issues/412.

feat: function to cleanup allocated resources after usage

---

.editorconfig
.gitattributes
.gitignore
lib/range.js
lib/source.js
lib/v8-to-istanbul.js
tap-snapshots/test/v8-to-istanbul.js.test.cjs
test/range.js
test/source.js

@bcoe this PR focuses only on #159 
please notice that I had to fix the shebang snapshot, I investigated the differences and it looks like before it was reporting 2 branches (wasn't it wrong?) while now there is only one

Optimized ranges (fix for issue #150)

---

README.md
index.d.ts
lib/source.js
lib/v8-to-istanbul.js
package-lock.json
package.json
test/source.js

[trace-mapping](https://github.com/jridgewell/trace-mapping) is faster, smaller, and lighter than the `source-map` package, and doesn't require WASM, manual memory management, or async/await to use.
Fixes #185.

refactor!: migrate from source-map to TraceMap

---

.github/workflows/ci.yaml

I haven't verified locally, but with #186 this module should work fine on v18 as well

chore: test on node 18

---

README.md
lib/v8-to-istanbul.js
test/v8-to-istanbul.js

After #186, `destroy()` isn't necessary anymore.
Re: https://github.com/istanbuljs/v8-to-istanbul/pull/186#discussion_r853839303

refactor: remove destroy() behavior

---

lib/source.js
test/source.js

Adds support for ignore hints to contain more text content, e.g. reasoning for ignoring code.
Changes the patterns to check the start of the ignore hint only. No need to verify that the pattern actually stops. If this method does not work, let me know and I'll reimplement the patterns. 
Closes https://github.com/bcoe/c8/issues/181.

feat: ignore hint to support other content as well

---

README.md

Should have been updated in https://github.com/istanbuljs/v8-to-istanbul/pull/109

chore: update CI badge in README

---

test/fixtures/scripts/uncovered.js
test/v8-to-istanbul.js

- Adds test case for #74
While looking into possible bug related to `wrapperLength` usage with "empty coverage" case I noticed there is no test case for #74.

test: empty coverage

---

lib/v8-to-istanbul.js
test/fixtures/scripts/ignored.lines.js
test/v8-to-istanbul.js

fix: ignore hint to mark uncovered files statements and lines

---

lib/v8-to-istanbul.js
test/v8-to-istanbul.js

fix: no wrapperLength for empty coverage

---

README.md
lib/source.js
test/source.js

- Closes #215
Adds support for `/* v8 ignore ...` ignore hints. For backwards compatibility the old `/* c8 ignore ...` is still supported.
Test cases contain plenty of whitespace changes caused by indentation bump. I recommend to hide whitespaces on the diff.

feat: support `/* v8 ignore` ignore hints

---

lib/source.js
test/source.js

This respects the `node:coverage` comments as used by the node:test coverage reporter.
- `node:coverage disable` -> `c8 ignore start`
- `node:coverage enable` -> `c8 ignore stop`
- `node:coverage ignore next` -> `c8 ignore ignore next`
- `node:coverage ignore next N` -> `c8 ignore ignore next N`

feat: respect node:coverage comments
